<?php
// var_dump($this);
if (is_array($this->menu)) {
    echo '<ul data-role="listview" data-inset="true">';
    foreach ($this->menu as $value) {
        $urlConfig = array(
            'controller' => $value['controller'],
            'action' => $value['action'],
        );
        if (is_array($value['options'])) {
            foreach ($value['options'] as $key => $opt) {
                $urlConfig[$key] = $opt;
            }
        }
        echo '<li><a href="', $this->url($urlConfig);
        echo "\">" . $value['label'] . "</a></li>";
    }
    echo "</ul>";
}
?>