<?php
// var_dump($this->cases);
    if (is_array($this->cases) && count($this->cases) > 0) {
        echo "<ul data-role=\"listview\" data-inset=\"true\" data-filter=\"true\">\n";
        foreach ($this->cases as $case) {
            echo "<li><a href=\"";
            echo $this->url(array(
                'controller'    => 'index',
                'action'        => 'view-case',
                'id'            => $case['id']
            ));
            echo "\">Дело № ", $case['number'], "</a></li>";
        }
        echo "</ul>";
    } else {
        echo "Няма дела!";
    }
    // echo $this->form;
    // echo '<ul data-role="listview" data-inset="true">';
    // if (!empty($this->case) && is_array($this->case)) {
        // $urlConfig = array(
            // 'controller'    => 'index',
            // 'action'        => 'view',
            // 'options'       => array(
                // 'id' => $this->case[0]['id'],
            // ),
        // );
        // echo '<li><a href="' . $this->url($urlConfig);
        // echo '">' . $this->case[0]['number']

    // } else {

    // }
?>